export { default as Home } from './Home/Home'
export { default as About } from './About/About'
export { default as Services } from './Services/Services'
export { default as Projects } from './Projects/Projects'
export { default as NoMatch } from './NoMatch/NoMatch'
export { default as UnderConstruction } from './UnderConstruction/UnderConstruction'